#!/bin/bash -eu
SCRIPT="$(basename "$0")"

function print_help () {
    cat << EOL
$SCRIPT: automatic dropbear-initramfs installer.
Usage: $0 [OPTIONS...]

Options:
  -k, --pubkey: pubkey path (if empty generate new key)
  -p, --port: dropber port.
  -n, --no-config: without auto dropbear config.
  -h, --help: Show this help.
EOL
}

if [[ "$(id -u)" -ne 0 ]];then
    print_help
    echo ""
    echo "$SCRIPT: require root."
    exit 1
fi

pubkey=""
port="22"
config=true
while [[ $# -gt 0 ]]; do
    case "$1" in
        -k | --pubkey ) pubkey="$2"; shift; shift;;
        -p | --port ) port="$2"; shift; shift;;
        -n | --no-config ) config=false; shift;;
        -v | --varbose) set -x; shift;; # 隠し
        -h | --help | *) print_help ; exit;;
    esac
done

: "dropbear" && {
    apt install -y "dropbear-initramfs"
    if $config;then
      sed -i "/^DROPBEAR_OPTIONS=/s/^/DROPBEAR_OPTIONS=\"-I 180 -p ${port} -j -k -s\"\n#/" /etc/dropbear/initramfs/dropbear.conf
    fi
}

: "pubkey" && {
    if [[ -z "$pubkey" ]];then
        ssh-keygen -t ed25519 -f "dropbear"
        pubkey="dropbear.pub"
    fi
    if [[ ! -f "$pubkey" ]];then
        echo "pubkey: ${pubkey} is not found!"
        exit 1
    fi
    echo -n 'command="cryptroot-unlock",no-port-forwarding,no-agent-forwarding,no-X11-forwarding ' >> /etc/dropbear/initramfs/authorized_keys
    cat "$pubkey" >> /etc/dropbear/initramfs/authorized_keys
}

update-initramfs -u
